# Generated by Django 5.2.1 on 2025-05-24 05:36

import avisos.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('robo_casa', 'Robo a Casa'), ('robo_vehiculo', 'Robo de Vehículo'), ('asalto', 'Asalto'), ('vehiculo_sospechoso', 'Vehículo Sospechoso'), ('persona_sospechosa', 'Persona Sospechosa'), ('accidente', 'Accidente de Tránsito'), ('emergencia_medica', 'Emergencia Médica'), ('incendio', 'Incendio'), ('vandalismo', 'Vandalismo'), ('problema_electrico', 'Problema Eléctrico'), ('otros', 'Otros')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Aviso',
                'verbose_name_plural': 'Tipos de Avisos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'El título debe tener al menos 5 caracteres')])),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'La descripción debe tener al menos 10 caracteres')])),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('resuelto', 'Resuelto'), ('en_proceso', 'En Proceso')], default='activo', max_length=15)),
                ('direccion', models.CharField(max_length=300)),
                ('sector', models.CharField(help_text='Ej: Costa Laguna, Manzana A, Block 15', max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, help_text='Teléfono de contacto opcional', max_length=17, validators=[django.core.validators.RegexValidator(message='Formato válido: +56912345678 o 912345678 (celular chileno)', regex='^(\\+56|56)?9[0-9]{8}$')])),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avisos/%Y/%m/')),
                ('es_anonimo', models.BooleanField(default=False)),
                ('verificado_por_admin', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='avisos.tipoaviso')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(3, 'El comentario debe tener al menos 3 caracteres')])),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='avisos.aviso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAsalto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asaltantes', models.PositiveIntegerField(default=1, verbose_name='Cantidad de asaltantes')),
                ('descripcion_fisica', models.TextField(blank=True, help_text='Incluye altura aproximada, contextura, vestimenta, rasgos distintivos, etc.', verbose_name='Descripción física de los asaltantes')),
                ('vehiculo_usado', models.CharField(blank=True, help_text='Marca, modelo, color y patente si es posible', max_length=200, verbose_name='Vehículo usado')),
                ('direccion_huida', models.CharField(blank=True, help_text='¿Hacia dónde huyeron los asaltantes?', max_length=200, verbose_name='Dirección de huida')),
                ('armas_usadas', models.CharField(blank=True, help_text='Tipo de armas que portaban los asaltantes', max_length=200, verbose_name='Armas utilizadas')),
                ('aviso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_asalto', to='avisos.aviso')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Ingrese RUT en formato 12.345.678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato válido: 12.345.678-9 o 12345678-9', regex='^[0-9]{1,2}\\.?[0-9]{3}\\.?[0-9]{3}-[0-9Kk]$'), avisos.models.validar_rut_chileno])),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Formato válido: +56912345678 o 912345678', regex='^(\\+56|56)?9[0-9]{8}$')])),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
