# Generated by Django 5.2.1 on 2025-05-24 23:05

import avisos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to=avisos.models.user_directory_path, verbose_name='Foto de perfil'),
        ),
    ]
